spring.application.name=HospitalManagementSystem


spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=ahtisham12


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


